server:
  address: 0.0.0.0
  port: 25995
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
  http2:
    enabled: false
  ssl:
    enabled: false

lavalink:
  server:
    password: youshallnotpass
    playerUpdateInterval: 5
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    trackStuckThresholdMs: 10000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    useSeekGhosting: true
    gc-warnings: true
    soundcloudSearchEnabled: true
    youtubeSearchEnabled: true
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
      nico: true
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
  plugins:
    - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
    - dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.2.10
    - dependency: dependency: dev.lavalink.youtube:youtube-plugin:1.8.3
    - dependency: dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1

plugins:
  lavasrc:
    sources:
      spotify: true
      youtube: true
      applemusic: false
      deezer: false
      flowerytts: false
      yandexmusic: false
    spotify:
      clientId: addurown
      clientSecret: addurown
  youtube:
    enabled: true

logging:
  level:
    root: INFO
    lavalink: INFO
  file:
    path: ./logs/

logback:
  rollingpolicy:
    max-file-size: 1GB
    max-history: 30

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: 
  environment:
