lavalink:
    clients:
        - MUSIC
        - ANDROID_TESTSUITE
        - WEB
        - TVHTML5EMBEDDED
    plugins:
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:4.2.0
        repository: https://maven.lavalink.dev/releases
        snapshot: false
        - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
        snapshot: false # Set to true if you want to use a snapshot version.
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 10
        password: youshallnotpass
        pasword: harumi.tech
        playerUpdateInterval: 5
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
level:
    lavalink: INFO
    root: INFO
logback:
    rollingpolicy:
        max-file-size: 1GB
        max-history: 30
request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includePayload: true
    includeQueryString: true
    maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        enabled: true
    spotify:
        enabled: true
        clientId: "your_spotify_client_id"
        clientSecret: "your_spotify_client_secret"
    deezer:
        enabled: true
        playlistLoadLimit: 5
        albumLoadLimit: 5
        artistLoadLimit: 5
    appleMusic:
        enabled: true
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 25995
    # Additional server configurations for optimization
    ssl:
        enabled: false
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json